spring:
  # 设置数据库连接解基本信息
  datasource:
    url: jdbc:mysql://localhost:3306/huawei
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 1800000
    host: 124.222.215.244
    port: 6379
    # redis密码
    password: cz1234
    lettuce:
      pool:
        # 最大连接数
        max-active: 30
        # 阻塞等待时间
        max-wait: 30
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 5